name: pyomo-doe-maint
channels:
  - conda-forge
  - IDAES-PSE
dependencies:
  - python=3.11
  - idaes-pse
  - pandas
  - numpy
  - matplotlib
  - scipy
  - ipykernel
  - nbformat
  - nodejs
  - pip
  - pip:
      - jupyter-book
      - black[jupyter]
